Algoritmo "Exemplo 1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Renato
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gisele Leite de Deus
// Data atual  : 21/03/2023
Var
 n1,n2,soma: real

Inicio

escreva("digite um número")
leia(n1)
escreva("digite um número")
leia(n2)
soma <- n1+n2;
escreval("primeiro número=",n1)
escreval("segundo número=",n2)
escreval("soma=",soma)

Fimalgoritmo